<?php
/** Individual locksmith service and city-service page. */
$category_slug = sanitize_title( get_query_var( 'mlp_service_category' ) );
$service_slug  = sanitize_title( get_query_var( 'mlp_service_item' ) );
$area_slug     = sanitize_title( get_query_var( 'mlp_service_area' ) );
$item          = mlp_get_service_item( $category_slug, $service_slug );
$area          = $area_slug ? mlp_get_service_area_record( $area_slug ) : null;
$place         = $area ? $area['name'] : 'Southeast Michigan';
$local_suffix  = $area ? ' in ' . $place : '';
$category_post = get_page_by_path( $category_slug, OBJECT, 'mlp_service' );
get_header();
?>
<main class="service-detail-main" id="main-content">
	<section class="service-detail-hero section-shell">
		<nav class="breadcrumb" aria-label="Breadcrumb"><a href="<?php echo esc_url( mlp_home_section_url( 'home' ) ); ?>">Home</a><span>/</span><?php if ( $area ) : ?><a href="<?php echo esc_url( mlp_get_service_area_url( $area['name'] ) ); ?>"><?php echo esc_html( $area['name'] ); ?></a><span>/</span><?php endif; ?><a href="<?php echo esc_url( $category_post ? get_permalink( $category_post ) : mlp_home_section_url( 'services' ) ); ?>"><?php echo esc_html( $item['category']['title'] ); ?></a><span>/</span><span aria-current="page"><?php echo esc_html( $item['name'] ); ?></span></nav>
		<div class="service-detail-hero-grid"><div class="service-detail-hero-copy"><p class="eyebrow"><span></span><?php echo esc_html( $item['category']['title'] ); ?></p><h1><?php echo esc_html( $item['name'] ); ?><em><?php echo esc_html( $local_suffix ? $local_suffix . '.' : '.' ); ?></em></h1><p><?php echo esc_html( $item['description'] ); ?> MI Lock Pros provides mobile service<?php echo esc_html( $area ? ' for customers in ' . $place . ', Michigan' : ' across Ann Arbor, Detroit, and Southeast Michigan' ); ?>.</p><div class="hero-actions"><a class="button button-primary button-large" href="<?php echo esc_url( mlp_phone_href() ); ?>"><svg class="button-phone-icon" aria-hidden="true" viewBox="0 0 24 24"><path d="M7.1 3.5 4.6 4.7c-.8.4-1.2 1.3-1 2.2 1.2 6.7 6.4 11.9 13.1 13.1.9.2 1.8-.2 2.2-1l1.2-2.5c.3-.7.1-1.5-.5-1.9l-3.1-2.1c-.6-.4-1.4-.3-1.9.2l-1.2 1.2a13 13 0 0 1-3.3-3.3l1.2-1.2c.5-.5.6-1.3.2-1.9L9.4 4.1c-.5-.7-1.5-.9-2.3-.6Z"/></svg>Call <?php echo esc_html( mlp_get_option( 'phone' ) ); ?></a><a class="button button-secondary button-large" href="<?php echo esc_url( mlp_home_section_url( 'request-service' ) ); ?>">Request Service</a></div></div>
			<aside class="service-detail-facts"><div><small>Availability</small><strong>Call to confirm current coverage</strong></div><div><small>Service type</small><strong>Mobile—we come to you</strong></div><div><small>Estimate</small><strong>Scope and price confirmed before work</strong></div><div><small>Authorization</small><strong>Proof may be required</strong></div></aside></div>
	</section>
	<div class="service-detail-assurance section-shell"><span>Insured</span><span>Background-checked technicians</span><span>Serving Southeast Michigan</span></div>
	<section class="service-detail-overview section-shell">
		<div class="service-detail-list-block"><p class="eyebrow"><span></span> When this service helps</p><h2>Clear options for the problem at hand.</h2><ul><li>You need <?php echo esc_html( strtolower( $item['name'] ) ); ?> for an authorized vehicle, home, or business.</li><li>A key, lock, fob, door, or access system is not working as expected.</li><li>You want a compatible replacement, spare, repair, or security improvement.</li><li>You need the work explained and priced before it begins.</li></ul></div>
		<div class="service-detail-list-block"><p class="eyebrow"><span></span> What is included</p><h2>Professional assessment and verification.</h2><ul class="included-list"><li>The exact lock, key, door, vehicle, or hardware is assessed.</li><li>Compatibility and available options are explained.</li><li>Authorization is confirmed when access or key work requires it.</li><li>Completed functions are checked before the technician leaves.</li></ul></div>
	</section>
	<section class="service-detail-process section-shell"><div class="service-detail-section-heading"><p class="eyebrow"><span></span> How it works</p><h2>From your call to the final check.</h2><p>Availability, parts, programming support, and service time depend on the exact situation. Call with the details so MI Lock Pros can confirm the right next step.</p></div><ol><li><span>01</span><div><strong>Share the details</strong><p>Provide the ZIP code, requested service, and the vehicle year, make, model, lock, or door details that apply.</p></div></li><li><span>02</span><div><strong>Confirm authorization</strong><p>Be prepared to show identification or proof that you are allowed to request access, key, or lock work.</p></div></li><li><span>03</span><div><strong>Review the options</strong><p>The technician assesses compatibility and confirms the proposed work and price before beginning.</p></div></li><li><span>04</span><div><strong>Complete and test</strong><p>The requested work is completed and the relevant key, lock, remote, door, or access functions are checked.</p></div></li></ol></section>
	<section class="service-quote section-shell"><div><p class="eyebrow"><span></span> Request a quote</p><h2>Need <?php echo esc_html( strtolower( $item['name'] ) . $local_suffix ); ?>?</h2><p>Call for a quote based on your location, the exact service, compatibility, and any parts or programming required.</p></div><div class="hero-actions"><a class="button button-primary button-large" href="<?php echo esc_url( mlp_phone_href() ); ?>">Call Now</a><a class="button button-secondary button-large" href="<?php echo esc_url( mlp_home_section_url( 'request-service' ) ); ?>">Request Service</a></div></section>
	<section class="service-detail-faq section-shell"><div class="service-detail-section-heading"><p class="eyebrow"><span></span> Common questions</p><h2><?php echo esc_html( $item['name'] ); ?>, explained.</h2></div><div class="faq-list"><details open><summary>Do you provide <?php echo esc_html( strtolower( $item['name'] ) . $local_suffix ); ?>?<span>+</span></summary><p><?php echo esc_html( $area ? $place . ' is within the listed mobile service area. ' : '' ); ?>Call with the exact location and job details so current coverage and compatibility can be confirmed.</p></details><details><summary>How much does the service cost?<span>+</span></summary><p>Pricing depends on the exact vehicle, key, lock, door, hardware, parts, programming, and job conditions. The scope and total are confirmed before authorized work begins.</p></details><details><summary>What should I have ready?<span>+</span></summary><p>Have the service ZIP code, a description of the problem, and any relevant vehicle or hardware details. Proof of ownership or authorization may be required.</p></details></div></section>
</main>
<?php get_footer(); ?>
