<?php /** Supported vehicle makes directory. */ $makes = mlp_vehicle_makes(); get_header(); ?>
<main class="vehicle-main" id="main-content">
	<section class="vehicle-index-hero section-shell"><p class="eyebrow"><span></span> Automotive key coverage</p><h1>Vehicles we may be able to make <em>keys and fobs for.</em></h1><p>Select a manufacturer to see the model families supplied by MI Lock Pros. Available automotive locksmith work may include car key replacement, spare key duplication, transponder key programming, key fob programming, and compatible push-to-start smart keys.</p><div class="hero-actions"><a class="button button-primary button-large" href="<?php echo esc_url( mlp_phone_href() ); ?>"><svg class="button-phone-icon" aria-hidden="true" viewBox="0 0 24 24"><path d="M7.1 3.5 4.6 4.7c-.8.4-1.2 1.3-1 2.2 1.2 6.7 6.4 11.9 13.1 13.1.9.2 1.8-.2 2.2-1l1.2-2.5c.3-.7.1-1.5-.5-1.9l-3.1-2.1c-.6-.4-1.4-.3-1.9.2l-1.2 1.2a13 13 0 0 1-3.3-3.3l1.2-1.2c.5-.5.6-1.3.2-1.9L9.4 4.1c-.5-.7-1.5-.9-2.3-.6Z"/></svg>Call to Confirm</a><a class="button button-secondary button-large" href="<?php echo esc_url( mlp_home_section_url( 'request-service' ) ); ?>">Request Service</a></div></section>
	<div class="vehicle-confirm section-shell"><span class="vehicle-confirm-icon">!</span><div><strong>Call to confirm your exact vehicle before requesting service.</strong><p>This guide is not a complete compatibility list. Model year, trim, key system, immobilizer, available tools, parts, and current coverage can affect whether service is available. MI Lock Pros may support additional models not shown here.</p></div><a href="<?php echo esc_url( mlp_phone_href() ); ?>"><?php echo esc_html( mlp_get_option( 'phone' ) ); ?><span class="theme-arrow" aria-hidden="true"></span></a></div>
	<section class="vehicle-directory section-shell"><div class="vehicle-section-heading"><div><p class="eyebrow"><span></span><?php echo esc_html( count( $makes ) ); ?> manufacturers</p><h2>Choose a vehicle make.</h2></div><p>Manufacturer logos are used only to help visitors identify their vehicle. MI Lock Pros is an independent locksmith and is not affiliated with or endorsed by these manufacturers.</p></div><div class="vehicle-logo-grid"><?php foreach ( $makes as $make ) : ?><a class="vehicle-logo-card" href="<?php echo esc_url( home_url( '/vehicles/' . $make['slug'] . '/' ) ); ?>"><span class="vehicle-logo-frame"><img src="<?php echo esc_url( $make['logo'] ); ?>" alt="<?php echo esc_attr( $make['name'] . ' logo' ); ?>" loading="lazy"></span><span class="vehicle-logo-copy"><strong><?php echo esc_html( $make['name'] ); ?></strong><small><?php echo esc_html( count( $make['models'] ) ); ?> listed models</small></span><span class="vehicle-card-arrow theme-arrow" aria-hidden="true"></span></a><?php endforeach; ?></div></section>
	<p class="vehicle-trademark-note section-shell">All trademarks, model names, and logos belong to their respective owners. Coverage depends on the exact vehicle and is confirmed by MI Lock Pros before work begins.</p>
	<section class="vehicle-services section-shell"><div class="vehicle-section-heading"><div><p class="eyebrow"><span></span> Automotive services</p><h2>Key services for supported vehicles.</h2></div><p>Choose a service for more information, then call with the vehicle year, make, model, and whether a working key is available.</p></div><div class="vehicle-service-grid"><?php foreach ( mlp_vehicle_key_services() as $service ) : ?><a href="<?php echo esc_url( mlp_service_item_url( 'automotive-locksmith', $service['name'] ) ); ?>"><small>Automotive locksmith</small><strong><?php echo esc_html( $service['name'] ); ?></strong><p><?php echo esc_html( $service['description'] ); ?></p><span>View service details</span></a><?php endforeach; ?></div></section>
</main>
<?php get_footer(); ?>
