<?php /** Vehicle manufacturer detail page. */ $make = mlp_get_vehicle_make( sanitize_title( get_query_var( 'mlp_vehicle_make' ) ) ); get_header(); ?>
<main class="vehicle-main" id="main-content">
	<section class="vehicle-make-hero section-shell"><nav class="breadcrumb" aria-label="Breadcrumb"><a href="<?php echo esc_url( mlp_home_section_url( 'home' ) ); ?>">Home</a><span>/</span><a href="<?php echo esc_url( home_url( '/vehicles/' ) ); ?>">Vehicles</a><span>/</span><span aria-current="page"><?php echo esc_html( $make['name'] ); ?></span></nav><div class="vehicle-make-hero-grid"><div><p class="eyebrow"><span></span>Vehicle key guide</p><h1><?php echo esc_html( $make['name'] ); ?> key and fob <em>service.</em></h1><p><?php echo esc_html( $make['summary'] ); ?> Select a model below, then call with the exact year and key situation so compatibility can be confirmed.</p><div class="hero-actions"><a class="button button-primary button-large" href="<?php echo esc_url( mlp_phone_href() ); ?>"><svg class="button-phone-icon" aria-hidden="true" viewBox="0 0 24 24"><path d="M7.1 3.5 4.6 4.7c-.8.4-1.2 1.3-1 2.2 1.2 6.7 6.4 11.9 13.1 13.1.9.2 1.8-.2 2.2-1l1.2-2.5c.3-.7.1-1.5-.5-1.9l-3.1-2.1c-.6-.4-1.4-.3-1.9.2l-1.2 1.2a13 13 0 0 1-3.3-3.3l1.2-1.2c.5-.5.6-1.3.2-1.9L9.4 4.1c-.5-.7-1.5-.9-2.3-.6Z"/></svg>Call to Confirm</a><a class="button button-secondary button-large" href="<?php echo esc_url( mlp_home_section_url( 'request-service' ) ); ?>">Request Service</a></div></div><div class="vehicle-make-logo"><img src="<?php echo esc_url( $make['logo'] ); ?>" alt="<?php echo esc_attr( $make['name'] . ' logo' ); ?>"></div></div></section>
	<div class="vehicle-confirm section-shell"><span class="vehicle-confirm-icon">!</span><div><strong>The list is a guide, not a guarantee of compatibility.</strong><p>MI Lock Pros may support additional <?php echo esc_html( $make['name'] ); ?> models or may be unable to service a listed vehicle because of the model year, system, parts, or current tools. Always call before relying on this list.</p></div><a href="<?php echo esc_url( mlp_phone_href() ); ?>">Call <?php echo esc_html( mlp_get_option( 'phone' ) ); ?><span class="theme-arrow" aria-hidden="true"></span></a></div>
	<section class="vehicle-models section-shell"><div class="vehicle-section-heading"><div><p class="eyebrow"><span></span><?php echo esc_html( count( $make['models'] ) ); ?> model families</p><h2>Listed <?php echo esc_html( $make['name'] ); ?> models.</h2></div><p>Service can vary by production year, generation, trim, key type, and immobilizer. A working key may make some spare-key services different from an all-keys-lost job.</p></div><ul class="vehicle-model-grid"><?php foreach ( $make['models'] as $model ) : ?><li><span>✓</span><strong><?php echo esc_html( $model ); ?></strong><small>Call to confirm year and system</small></li><?php endforeach; ?></ul></section>
	<section class="vehicle-call-prep section-shell"><div><p class="eyebrow"><span></span> Before you call</p><h2>Have the right details ready.</h2></div><ol><li><span>01</span><div><strong>Year, make, and model</strong><p>Share the full vehicle details, including trim when known.</p></div></li><li><span>02</span><div><strong>Working-key status</strong><p>Tell us whether every key is lost or at least one working key is available.</p></div></li><li><span>03</span><div><strong>Key and ignition type</strong><p>Describe a blade key, remote-head key, key fob, push-to-start smart key, or ignition problem.</p></div></li><li><span>04</span><div><strong>Location and authorization</strong><p>Provide the service ZIP code and be ready to verify ownership or authorization.</p></div></li></ol></section>
	<section class="vehicle-final-cta section-shell"><div><p class="eyebrow"><span></span> Confirm compatibility</p><h2>Need a key for a <?php echo esc_html( $make['name'] ); ?>?</h2><p>Call MI Lock Pros with the exact vehicle and key situation. We will confirm whether we can currently perform the requested work.</p></div><div class="hero-actions"><a class="button button-primary button-large" href="<?php echo esc_url( mlp_phone_href() ); ?>">Call Now</a><a class="button button-secondary button-large" href="<?php echo esc_url( mlp_home_section_url( 'request-service' ) ); ?>">Request Service</a></div></section>
</main>
<?php get_footer(); ?>
